### model
model_name_or_path: models/Qwen3-0.6B
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target: all

### dataset
dataset: code_contests_py3_sft_train
template: qwen3_nothink
enable_thinking: false
cutoff_len: 4096
max_samples: 64
overwrite_cache: true
preprocessing_num_workers: 4
dataloader_num_workers: 0

### output
output_dir: saves/qwen3-0.6b/lora/code_contests_py3_sft_10
logging_steps: 1
save_steps: 5
plot_loss: true
overwrite_output_dir: true
report_to: none
run_name: qwen3-0.6b-code-contests-py3-sft-10

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 1.0e-5
max_steps: 10
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
